### ISSUE TITLE
exit

### ISSUE THREAD

**Issue by ili101** [lkrms/pretty-php#99]
```php
<?php

exit();
die();
```
Incorrectly changes to:
```php
<?php

exit ();
die ();
```

**Comment by lkrms** [comment]
Thanks for your feedback on this.

This behaviour isn't "incorrect" per se--the space is inserted because `exit ()` is a language construct, not a function call--but `exit`/`die` is a special case and I'm open to changing it.

For context, `pretty-php` inserts a space after language constructs that are valid without subsequent parentheses:

```php
<?php
exit;
exit ();
exit (0);
require 'config.php';
require ('config.php');
print 'Hello, world!' . PHP_EOL;
print ('Hello, world!' . PHP_EOL);
```

`exit`/`die` is "special" because it can be used without parentheses if no `$status` is passed, but if a `$status` is passed, parentheses are mandatory.

We could insert a space only before empty parentheses, to indicate they are unnecessary:

```php
<?php
exit;
exit ();
exit(0);
```

But that would trade visual consistency for technical consistency (and seems rather silly 😜).

On balance, treating `exit`/`die` like a function call is probably the best way forward. I'll action this soon.

**Comment by ili101** [comment]
Yes I see, language constructs spaces were never defined. The commands with official examples in https://www.php.net/manual/en/reserved.keywords.php are usually used as in the example but not always.
